name: Deploy Azure Function

on:
  push:
    branches: ["main"] # Altere se sua branch principal tiver outro nome

env:
  AZURE_FUNCTIONAPP_NAME: 'NOME_DA_SUA_APP' # Coloque o nome da sua Function App aqui
  PACKAGE_PATH: 'azure_function'           # Importante: aponta para a subpasta correta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - setup-python: '3.11'
      
      - name: 'Install dependencies'
        run: |
          pushd './${{ env:PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages"
          popd

      - name: 'Deploy to Azure'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env:AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env:PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
